version: 2

jobs:

  buildImage:
    docker:
      - image: web3f/ci-commons:v2.4.8
    resource_class: xlarge  
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            /scripts/build-image.sh web3f/1k-watcher-claimed-payouts .

  publishImage:
    docker:
      - image: web3f/ci-commons:v2.4.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/1k-watcher-claimed-payouts

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.4.8
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.4.8
    resource_class: large    
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh          

  deploy:
      docker:
        - image: web3f/ci-commons:v2.4.8
      steps:
        - checkout
        - run:
            environment:
              HELM_ENV: production
            command: |
              /scripts/deploy.sh -c community          

workflows:
  version: 2
  test_and_deploy:
    jobs:   
      - buildImage:
          context: dockerhub-bot
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/   
          requires:
            - buildImage        
      - publishImage:
          context: dockerhub-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - buildImage
      - publishChart:
          context: github-bot
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - buildImage
      - deploy:
          context: 
            - digital_ocean_access
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/
          requires:
            - publishImage
            - publishChart      
